// Generated by tools/make_thumbs.py: menu thumbnail atlas name -> path.
public abstract class HomesteadAtlas {
    public static func Path(name: String) -> ResRef {
        if Equals(name, "0") { return r"homestead\\ui\\thumbs_0.inkatlas"; }
        if Equals(name, "1") { return r"homestead\\ui\\thumbs_1.inkatlas"; }
        if Equals(name, "2") { return r"homestead\\ui\\thumbs_2.inkatlas"; }
        if Equals(name, "3") { return r"homestead\\ui\\thumbs_3.inkatlas"; }
        if Equals(name, "4") { return r"homestead\\ui\\thumbs_4.inkatlas"; }
        if Equals(name, "5") { return r"homestead\\ui\\thumbs_5.inkatlas"; }
        if Equals(name, "6") { return r"homestead\\ui\\thumbs_6.inkatlas"; }
        if Equals(name, "7") { return r"homestead\\ui\\thumbs_7.inkatlas"; }
        if Equals(name, "8") { return r"homestead\\ui\\thumbs_8.inkatlas"; }
        if Equals(name, "9") { return r"homestead\\ui\\thumbs_9.inkatlas"; }
        if Equals(name, "10") { return r"homestead\\ui\\thumbs_10.inkatlas"; }
        if Equals(name, "11") { return r"homestead\\ui\\thumbs_11.inkatlas"; }
        if Equals(name, "12") { return r"homestead\\ui\\thumbs_12.inkatlas"; }
        if Equals(name, "13") { return r"homestead\\ui\\thumbs_13.inkatlas"; }
        if Equals(name, "14") { return r"homestead\\ui\\thumbs_14.inkatlas"; }
        if Equals(name, "15") { return r"homestead\\ui\\thumbs_15.inkatlas"; }
        if Equals(name, "16") { return r"homestead\\ui\\thumbs_16.inkatlas"; }
        if Equals(name, "17") { return r"homestead\\ui\\thumbs_17.inkatlas"; }
        if Equals(name, "18") { return r"homestead\\ui\\thumbs_18.inkatlas"; }
        if Equals(name, "19") { return r"homestead\\ui\\thumbs_19.inkatlas"; }
        if Equals(name, "20") { return r"homestead\\ui\\thumbs_20.inkatlas"; }
        if Equals(name, "21") { return r"homestead\\ui\\thumbs_21.inkatlas"; }
        return r"homestead\\ui\\thumbs_0.inkatlas";
    }
}
