"""The player's release: dist/Homestead/ in the game folder's own layout, zipped to dist/Homestead-<version>.zip (a mod
manager, or the player, unpacks it into the Cyberpunk 2077 folder). Nothing of Bethesda's or CDPR's is in it: the
in-game settings run the bundled importer, which makes all that on the player's PC from their own games.
  python tools/release.py            (checks first - see stale() - and stops if anything is out of date)
  python tools/release.py --check    the checks alone
Needs PyInstaller, the plugin built (plugin/CMakeLists.txt), and the tools it bundles (homestead_paths.json or found:
wolvenkit, dotnet, and ffmpeg_lgpl - an LGPL-only ffmpeg build, https://github.com/BtbN/FFmpeg-Builds).
"""
import importlib, json, os, shutil, subprocess, sys, zipfile

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS); sys.path.insert(0, os.path.join(TOOLS, 'fo4'))
import paths

VERSION = '0.2.0'
ROOT = paths.ROOT
DIST = os.path.join(ROOT, 'dist')
OUT = os.path.join(DIST, 'Homestead')
CET = paths.CET
IMP = os.path.join(OUT, CET, 'importer')
# the importer's modules PyInstaller can't see (imported inside functions)
HIDDEN = ['convert', 'build', 'xbm', 'lights', 'sounds', 'furniture', 'anim', 'nif', 'bgsm', 'ba2', 'esm', 'budget',
          'make_workspots', 'make_weapons', 'make_ent', 'make_border', 'build_catalog', 'taxonomy', 'colliders', 'meshes', 'codehash', 'havok']
LICENSES = {                                                 # what's bundled, its licence, where its source is
    'WolvenKit CLI': ('GPL-3.0', 'https://github.com/WolvenKit/WolvenKit'),
    'networkx': ('BSD-3-Clause', 'https://github.com/networkx/networkx'),
    '.NET runtime': ('MIT', 'https://github.com/dotnet/runtime'),
    'FFmpeg (LGPL build)': ('LGPL-2.1+', 'https://github.com/BtbN/FFmpeg-Builds , https://ffmpeg.org/download.html'),
    'Python + NumPy, SciPy, Pillow, trimesh': ('PSF / BSD / BSD / MIT-CMU / MIT', 'https://pypi.org'),
}


def codehash():
    """the importer's steps' code hashes, baked in (the frozen importer has no .py files to read): from the source as
    it is now - never the codehash.py of the release before (it once copied that forward: no code change redid a step)"""
    imp = importlib.import_module('import')
    with open(os.path.join(TOOLS, 'codehash.py'), 'w', encoding='utf-8') as f:
        f.write('# Generated by tools/release.py: tools/import.py CODE hashes, for the frozen importer\nCODE = %r\n'
                % {s: imp.source_digest(s) for s in imp.CODE})


def build_id():
    """what an import's output depends on, as one hash: the steps' code, the catalog's and the archive's makers, and the
    data the importer ships. The mod compares it with the one its last import installed with (settings.lua
    Settings.stale): an update that changes none of it needs no import"""
    import hashlib
    imp = importlib.import_module('import')
    h = hashlib.sha1(repr(sorted((s, imp.source_digest(s)) for s in imp.CODE)).encode())
    for f in ('build_catalog.py', 'taxonomy.py', 'make_ent.py', 'import.py'): h.update(imp.meaning(os.path.join(TOOLS, f)).encode())
    data = [os.path.join(ROOT, 'source', 'catalog_native.json.gz'), os.path.join(ROOT, 'source', 'thumbs.json')]
    for d, _, fs in os.walk(os.path.join(ROOT, 'source', 'json', 'homestead', 'ui')): data += [os.path.join(d, f) for f in sorted(fs)]
    for f in data: h.update(open(f, 'rb').read())
    return h.hexdigest()[:12]


# all the importer imports, pinned (what build/venv has, 2026-10-03): a newer trimesh or scipy could change collision
# boxes between releases (trimesh's dump(concatenate=True) is deprecated) - the venv is made from these once
REQUIRES = ['numpy==1.26.4', 'scipy==1.17.1', 'pillow==12.3.0', 'trimesh==5.1.0', 'networkx==3.4.2', 'pyinstaller==6.22.3']   # (networkx: trimesh's split/fill_holes want it - the first Havok import failed without it)


def freeze():
    """the importer as HomesteadImport.exe (no window), frozen from a venv of its own: frozen from a Python with more
    in it, trimesh's optional imports pulled in gigabytes (torch, OpenCV...)"""
    work = os.path.join(ROOT, 'build')
    venv = os.path.join(work, 'venv')
    py = os.path.join(venv, 'Scripts', 'python.exe')
    if not os.path.exists(py):
        subprocess.run([sys.executable, '-m', 'venv', venv], check=True)
        subprocess.run([py, '-m', 'pip', 'install', '-q'] + REQUIRES, check=True)
    cmd = [py, '-m', 'PyInstaller', '--noconfirm', '--clean', '--noconsole', '--name', 'HomesteadImport',
           '--distpath', os.path.join(work, 'pyi'), '--workpath', os.path.join(work, 'pyi_work'), '--specpath', work,
           '--paths', TOOLS, '--paths', os.path.join(TOOLS, 'fo4')]
    for h in HIDDEN: cmd += ['--hidden-import', h]
    cmd += ['--collect-submodules', 'networkx']          # (trimesh imports it lazily: PyInstaller can't see it)
    subprocess.run(cmd + [os.path.join(TOOLS, 'import.py')], check=True)
    return os.path.join(work, 'pyi', 'HomesteadImport')


def stale():
    """what would make the release wrong, before anything is built: the plugin older than its source, the catalog older
    than what it's made from (catalog_native.json.gz ships from the same build, and the sim tests that catalog), the
    sim failing -> the problems, each with what to do"""
    def newer(out, ins):                                     # the inputs changed since out was made
        t = os.path.getmtime(out) if os.path.exists(out) else 0
        return [os.path.basename(i) for i in ins if os.path.exists(i) and os.path.getmtime(i) > t]
    bad = []
    if newer(os.path.join(ROOT, 'plugin', 'build', 'Release', 'Homestead.dll'), [os.path.join(ROOT, 'plugin', 'Main.cpp')]):
        bad.append('the plugin is older than plugin/Main.cpp: cmake --build plugin/build --config Release')
    W = paths.work()
    ins = [os.path.join(TOOLS, f) for f in ('build_catalog.py', 'taxonomy.py')] + [os.path.join(W, *p) for p in (
        ('harvest', 'items.json'), ('harvest', 'shape.json'), ('harvest', 'lights.json'), ('survey', 'people.json'),
        ('survey', 'people_check.txt'), ('thumbs.json',), ('weapons.json',), ('fo4', 'pieces.json'))]
    late = newer(os.path.join(paths.out_cet(), 'catalog.lua'), ins)
    if late: bad.append('catalog.lua is older than %s: python tools/build_catalog.py' % ', '.join(late))
    r = subprocess.run([sys.executable, os.path.join(TOOLS, 'sim.py')], capture_output=True, text=True, errors='replace')
    fails = [l[5:] for l in r.stdout.splitlines() if l.startswith('FAIL')]
    if r.returncode or fails: bad.append('the sim fails: %s' % ('; '.join(fails[:3]) if fails else paths.said(r.stdout + r.stderr)))
    return bad


def copy(src, *rel):
    dst = os.path.join(OUT, *rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    (shutil.copytree if os.path.isdir(src) else shutil.copy2)(src, dst)


def main():
    if not os.path.exists(os.path.join(ROOT, 'plugin', 'build', 'Release', 'Homestead.dll')):
        sys.exit('build the plugin first: cmake -S plugin -B plugin/build && cmake --build plugin/build --config Release')
    bad = stale()
    if bad or '--check' in sys.argv: sys.exit(('not ready:\n  ' + '\n  '.join(bad)) if bad else 'ready')
    wk, dn = paths.get('wolvenkit'), paths.get('dotnet')
    ff = json.load(open(os.path.join(ROOT, 'homestead_paths.json'))).get('ffmpeg_lgpl') if os.path.exists(os.path.join(ROOT, 'homestead_paths.json')) else None
    if not ff or not os.path.exists(ff): sys.exit('say where an LGPL ffmpeg.exe is: homestead_paths.json "ffmpeg_lgpl"')
    codehash()
    frozen = freeze()
    shutil.rmtree(OUT, ignore_errors=True)
    # the mod: CET Lua, scripts, tweaks, the RED4ext plugin
    copy(os.path.join(ROOT, CET, 'init.lua'), CET, 'init.lua')
    copy(os.path.join(ROOT, CET, 'modules'), CET, 'modules')
    for f in os.listdir(os.path.join(ROOT, 'r6', 'scripts', 'Homestead')):
        copy(os.path.join(ROOT, 'r6', 'scripts', 'Homestead', f), 'r6', 'scripts', 'Homestead', f)
    copy(os.path.join(ROOT, 'r6', 'tweaks', 'Homestead.yaml'), 'r6', 'tweaks', 'Homestead.yaml')
    copy(os.path.join(ROOT, 'plugin', 'build', 'Release', 'Homestead.dll'), 'red4ext', 'plugins', 'Homestead', 'Homestead.dll')
    # the importer, and what it brings
    shutil.copytree(frozen, IMP)
    copy(os.path.join(ROOT, 'source', 'catalog_native.json.gz'), CET, 'importer', 'data', 'catalog_native.json.gz')
    copy(os.path.join(ROOT, 'source', 'thumbs.json'), CET, 'importer', 'data', 'thumbs.json')   # the menu's thumbnails
    copy(os.path.join(ROOT, 'source', 'json', 'homestead', 'ui'), CET, 'importer', 'data', 'ui')   # (tools/make_thumbs.py)
    copy(os.path.dirname(wk), CET, 'importer', 'bin', 'WolvenKit-cli')
    copy(dn, CET, 'importer', 'bin', 'dotnet')
    copy(ff, CET, 'importer', 'bin', 'ffmpeg', 'ffmpeg.exe')
    lic = os.path.join(IMP, 'licenses')
    os.makedirs(lic, exist_ok=True)
    for f in ('LICENSE.txt', 'ThirdPartyNotices.txt'):
        if os.path.exists(os.path.join(dn, f)): shutil.copy2(os.path.join(dn, f), os.path.join(lic, 'dotnet_' + f))
    if os.path.exists(os.path.join(os.path.dirname(ff), 'LICENSE.txt')):
        shutil.copy2(os.path.join(os.path.dirname(ff), 'LICENSE.txt'), os.path.join(lic, 'ffmpeg_LICENSE.txt'))
    wkl = os.path.join(ROOT, 'tools', 'licenses', 'WolvenKit_LICENSE.txt')
    if os.path.exists(wkl): shutil.copy2(wkl, os.path.join(lic, 'WolvenKit_LICENSE.txt'))
    with open(os.path.join(lic, 'README.txt'), 'w', encoding='utf-8') as f:
        f.write('Homestead %s bundles these programs, unmodified, to make its pieces on your PC:\n\n' % VERSION)
        for name, (l, src) in LICENSES.items(): f.write('  %-58s %-22s source: %s\n' % (name, l, src))
    shutil.copy2(os.path.join(ROOT, 'README_PLAYER.txt'), os.path.join(OUT, CET, 'README.txt'))
    with open(os.path.join(OUT, CET, 'build.txt'), 'w') as f: f.write('build=%s\n' % build_id())
    # zipped
    z = os.path.join(DIST, 'Homestead-%s.zip' % VERSION)
    if os.path.exists(z): os.remove(z)
    with zipfile.ZipFile(z, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for d, _, fs in os.walk(OUT):
            for f in fs: zf.write(os.path.join(d, f), os.path.relpath(os.path.join(d, f), OUT))
    size = sum(os.path.getsize(os.path.join(d, f)) for d, _, fs in os.walk(OUT) for f in fs)
    print('%s: %.0f MB unpacked, %.0f MB zipped' % (z, size / 1e6, os.path.getsize(z) / 1e6))


if __name__ == '__main__':
    main()
